//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#ifndef EDROOMDEPLOYMENT_H_
#define EDROOMDEPLOYMENT_H_
 
#include <edroom_glue/edroomdf.h>
#include <public/edroomsl_iface_v1.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/ccserver_iface_v1.h>
#include <public/ccclient_iface_v1.h>
// ***********************************************************************
// class CEDROOMSystemMemory
// ***********************************************************************
 
class CEDROOMSystemMemory{
 
	//!Messages Memory of component comp2
	CEDROOMMessage	comp2Messages[10];
	bool	comp2MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp2QueueNodes[10];
	bool	comp2QueueNodesMarks[10];
 
	//!Messages Memory of component comp3
	CEDROOMMessage	comp3Messages[10];
	bool	comp3MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp3QueueNodes[14];
	bool	comp3QueueNodesMarks[14];
 
	//!Messages Memory of component comp4
	CEDROOMMessage	comp4Messages[10];
	bool	comp4MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp4QueueNodes[14];
	bool	comp4QueueNodesMarks[14];
 
	//!Messages Memory of component comp5
	CEDROOMMessage	comp5Messages[10];
	bool	comp5MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp5QueueNodes[14];
	bool	comp5QueueNodesMarks[14];
 
	//!Messages Memory of component comp6
	CEDROOMMessage	comp6Messages[10];
	bool	comp6MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp6QueueNodes[14];
	bool	comp6QueueNodesMarks[14];
 
	public:
 
	CCServer::CEDROOMMemory comp2Memory;
	CCClient::CEDROOMMemory comp3Memory;
	CCClient::CEDROOMMemory comp4Memory;
	CCClient::CEDROOMMemory comp5Memory;
	CCClient::CEDROOMMemory comp6Memory;
 
//!Set Memory
	void SetMemory();
};
 
class CEDROOMSystemCommSAP{
 
	 friend class CEDROOMSystemDeployment;
//!Communication Service Access Point
 
	CEDROOMLocalCommSAP m_localCommSAP;
 
 
//!Conections
 
	CEDROOMLocalConnection connections[4];
 
	CCServer   * mp_comp2;
	CCClient   * mp_comp3;
	CCClient   * mp_comp4;
	CCClient   * mp_comp5;
	CCClient   * mp_comp6;
 
 
//!Set Components
 
	void SetComponents(CCServer   *p_comp2,
							CCClient   *p_comp3,
							CCClient   *p_comp4,
							CCClient   *p_comp5,
							CCClient   *p_comp6);
 
 
//Signal Conversion
 
	static TEDROOMSignal C2Server_PpService4__C6Client4_PpSerReq(TEDROOMSignal signal);
	static TEDROOMSignal C6Client4_PpSerReq__C2Server_PpService4(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C2Server_PpService3__C5Client3_PpSerReq(TEDROOMSignal signal);
	static TEDROOMSignal C5Client3_PpSerReq__C2Server_PpService3(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C2Server_PpService2__C4Client2_PpSerReq(TEDROOMSignal signal);
	static TEDROOMSignal C4Client2_PpSerReq__C2Server_PpService2(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C2Server_PpService1__C3Client1_PpSerReq(TEDROOMSignal signal);
	static TEDROOMSignal C3Client1_PpSerReq__C2Server_PpService1(TEDROOMSignal signal);
 
 
//!Register Interfaces
	void RegisterInterfaces();
 
//!Set Local Connections
	void SetLocalConnections();
 
//!Set Remote Connections
	void SetRemoteConnections();
 
//!Set Connections
	void SetConnections();
 
};
 
class CEDROOMSystemDeployment{
 
//!Kernel
	Pr_Kernel	kernel;
 
#ifdef CONFIG_EDROOMDEPLOYMENT_NEED_TASK
 
//!Main Task
static Pr_TaskRV_t main_task(Pr_TaskP_t);
 
#endif
	CEDROOMSystemMemory   systemMemory;
	CEDROOMSystemCommSAP  systemCommSAP;
 
	CCServer   * mp_comp2;
	CCClient   * mp_comp3;
	CCClient   * mp_comp4;
	CCClient   * mp_comp5;
	CCClient   * mp_comp6;
 
	public:
 
	CEDROOMSystemDeployment();
 
//!Deployment Configuration
	void Config(CCServer   *p_comp2,
					CCClient   *p_comp3,
					CCClient   *p_comp4,
					CCClient   *p_comp5,
					CCClient   *p_comp6);
 
//!Deployment Start
	void Start();
 
//!StartComponents
	void StartComponents();
//!Config Components
 
	CCServer::CEDROOMMemory 		* GetComp2Memory(){return &systemMemory.comp2Memory;}
	CCClient::CEDROOMMemory 		* GetComp3Memory(){return &systemMemory.comp3Memory;}
	CCClient::CEDROOMMemory 		* GetComp4Memory(){return &systemMemory.comp4Memory;}
	CCClient::CEDROOMMemory 		* GetComp5Memory(){return &systemMemory.comp5Memory;}
	CCClient::CEDROOMMemory 		* GetComp6Memory(){return &systemMemory.comp6Memory;}
 
};
#endif
