//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#ifndef EDROOMDEPLOYMENT_H_
#define EDROOMDEPLOYMENT_H_
 
#include <edroom_glue/edroomdf.h>
#include <public/edroomsl_iface_v1.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/ccproducer_iface_v1.h>
#include <public/ccconsumer_iface_v1.h>
// ***********************************************************************
// class CEDROOMSystemMemory
// ***********************************************************************
 
class CEDROOMSystemMemory{
 
	//!Messages Memory of component comp2
	CEDROOMMessage	comp2Messages[10];
	bool	comp2MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp2QueueNodes[10];
	bool	comp2QueueNodesMarks[10];
 
	//!Messages Memory of component comp3
	CEDROOMMessage	comp3Messages[10];
	bool	comp3MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp3QueueNodes[13];
	bool	comp3QueueNodesMarks[13];
 
	public:
 
	CCProducer::CEDROOMMemory comp2Memory;
	CCConsumer::CEDROOMMemory comp3Memory;
 
//!Set Memory
	void SetMemory();
};
 
class CEDROOMSystemCommSAP{
 
	 friend class CEDROOMSystemDeployment;
//!Communication Service Access Point
 
	CEDROOMLocalCommSAP m_localCommSAP;
 
 
//!Conections
 
	CEDROOMLocalConnection connections[1];
 
	CCProducer   * mp_comp2;
	CCConsumer   * mp_comp3;
 
 
//!Set Components
 
	void SetComponents(CCProducer   *p_comp2,
							CCConsumer   *p_comp3);
 
 
//Signal Conversion
 
	static TEDROOMSignal C2Producer_PpOut__C3Consumer_PpIn(TEDROOMSignal signal);
	static TEDROOMSignal C3Consumer_PpIn__C2Producer_PpOut(TEDROOMSignal signal);
 
 
//!Register Interfaces
	void RegisterInterfaces();
 
//!Set Local Connections
	void SetLocalConnections();
 
//!Set Remote Connections
	void SetRemoteConnections();
 
//!Set Connections
	void SetConnections();
 
};
 
class CEDROOMSystemDeployment{
 
//!Kernel
	Pr_Kernel	kernel;
 
#ifdef CONFIG_EDROOMDEPLOYMENT_NEED_TASK
 
//!Main Task
static Pr_TaskRV_t main_task(Pr_TaskP_t);
 
#endif
	CEDROOMSystemMemory   systemMemory;
	CEDROOMSystemCommSAP  systemCommSAP;
 
	CCProducer   * mp_comp2;
	CCConsumer   * mp_comp3;
 
	public:
 
	CEDROOMSystemDeployment();
 
//!Deployment Configuration
	void Config(CCProducer   *p_comp2,
					CCConsumer   *p_comp3);
 
//!Deployment Start
	void Start();
 
//!StartComponents
	void StartComponents();
//!Config Components
 
	CCProducer::CEDROOMMemory 		* GetComp2Memory(){return &systemMemory.comp2Memory;}
	CCConsumer::CEDROOMMemory 		* GetComp3Memory(){return &systemMemory.comp3Memory;}
 
};
#endif
