//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#include <public/edroom_glue.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/ccproducer_iface_v1.h>
#include <public/ccconsumer_iface_v1.h>
 
#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
 
rtems_task Init (uint32_t arg){
 
 
 
#ifndef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
	CCProducer	comp2(2, 10, EDROOMprioNormal, 1024, systemDeployment.GetComp2Memory());
	CCConsumer	comp3(3, 13, EDROOMprioNormal, 1024, systemDeployment.GetComp3Memory());
 
	systemDeployment.Config(&comp2, &comp3);
 
	systemDeployment.Start();
 
	;
 
}
